/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: (typeof import("ant-design-vue/es"))["InputPassword"]
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATree: typeof import('ant-design-vue/es')['Tree']
    DragModal: typeof import('./src/components/dragModal.vue')['default']
    GroupRules: typeof import('./src/components/groupRules.vue')['default']
    IconSvg: typeof import('./src/components/IconSvg.vue')['default']
    ParticlesComponent: typeof import('./src/components/particlesComponent.vue')['default']
    RightMenu: typeof import('./src/components/rightMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SegmentedComponent: typeof import('./src/components/segmentedComponent.vue')['default']
    TableComponent: typeof import('./src/components/tableComponent.vue')['default']
    TableList: typeof import('./src/components/tableList.vue')['default']
  }
}
