const light = {
  0: {
    account: [
      require("./light/0/account/1.png"),
      require("./light/0/account/2.png"),
      require("./light/0/account/3.png"),
      require("./light/0/account/4.png"),
    ],
    airplane: [
      require("./light/0/airplane/1.png"),
      require("./light/0/airplane/2.png"),
      require("./light/0/airplane/3.png"),
      require("./light/0/airplane/4.png"),
    ],
    armoredVehicle: [
      require("./light/0/armoredVehicle/1.png"),
      require("./light/0/armoredVehicle/2.png"),
      require("./light/0/armoredVehicle/3.png"),
      require("./light/0/armoredVehicle/4.png"),
    ],
    car: [
      require("./light/0/car/1.png"),
      require("./light/0/car/2.png"),
      require("./light/0/car/3.png"),
      require("./light/0/car/4.png"),
    ],
    company: [
      require("./light/0/company/1.png"),
      require("./light/0/company/2.png"),
      require("./light/0/company/3.png"),
      require("./light/0/company/4.png"),
    ],
    cruiser: [
      require("./light/0/cruiser/1.png"),
      require("./light/0/cruiser/2.png"),
      require("./light/0/cruiser/3.png"),
      require("./light/0/cruiser/4.png"),
    ],
    default: [
      require("./light/0/default/1.png"),
      require("./light/0/default/2.png"),
      require("./light/0/default/3.png"),
      require("./light/0/default/4.png"),
    ],
    document: [
      require("./light/0/document/1.png"),
      require("./light/0/document/2.png"),
      require("./light/0/document/3.png"),
      require("./light/0/document/4.png"),
    ],
    event: [
      require("./light/0/event/1.png"),
      require("./light/0/event/2.png"),
      require("./light/0/event/3.png"),
      require("./light/0/event/4.png"),
    ],
    industry: [
      require("./light/0/industry/1.png"),
      require("./light/0/industry/2.png"),
      require("./light/0/industry/3.png"),
      require("./light/0/industry/4.png"),
    ],
    location: [
      require("./light/0/location/1.png"),
      require("./light/0/location/2.png"),
      require("./light/0/location/3.png"),
      require("./light/0/location/4.png"),
    ],
    missile: [
      require("./light/0/missile/1.png"),
      require("./light/0/missile/2.png"),
      require("./light/0/missile/3.png"),
      require("./light/0/missile/4.png"),
    ],
    organization: [
      require("./light/0/organization/1.png"),
      require("./light/0/organization/2.png"),
      require("./light/0/organization/3.png"),
      require("./light/0/organization/4.png"),
    ],
    person: [
      require("./light/0/person/1.png"),
      require("./light/0/person/2.png"),
      require("./light/0/person/3.png"),
      require("./light/0/person/4.png"),
    ],
    rocket: [
      require("./light/0/rocket/1.png"),
      require("./light/0/rocket/2.png"),
      require("./light/0/rocket/3.png"),
      require("./light/0/rocket/4.png"),
    ],
    ship: [
      require("./light/0/ship/1.png"),
      require("./light/0/ship/2.png"),
      require("./light/0/ship/3.png"),
      require("./light/0/ship/4.png"),
    ],
    train: [
      require("./light/0/train/1.png"),
      require("./light/0/train/2.png"),
      require("./light/0/train/3.png"),
      require("./light/0/train/4.png"),
    ],
  },
  1: {
    account: [
      require("./light/1/account/1.png"),
      require("./light/1/account/2.png"),
      require("./light/1/account/3.png"),
      require("./light/1/account/4.png"),
    ],
    airplane: [
      require("./light/1/airplane/1.png"),
      require("./light/1/airplane/2.png"),
      require("./light/1/airplane/3.png"),
      require("./light/1/airplane/4.png"),
    ],
    armoredVehicle: [
      require("./light/1/armoredVehicle/1.png"),
      require("./light/1/armoredVehicle/2.png"),
      require("./light/1/armoredVehicle/3.png"),
      require("./light/1/armoredVehicle/4.png"),
    ],
    car: [
      require("./light/1/car/1.png"),
      require("./light/1/car/2.png"),
      require("./light/1/car/3.png"),
      require("./light/1/car/4.png"),
    ],
    company: [
      require("./light/1/company/1.png"),
      require("./light/1/company/2.png"),
      require("./light/1/company/3.png"),
      require("./light/1/company/4.png"),
    ],
    cruiser: [
      require("./light/1/cruiser/1.png"),
      require("./light/1/cruiser/2.png"),
      require("./light/1/cruiser/3.png"),
      require("./light/1/cruiser/4.png"),
    ],
    default: [
      require("./light/1/default/1.svg"),
      require("./light/1/default/2.svg"),
      require("./light/1/default/3.svg"),
      require("./light/1/default/4.svg"),
    ],
    document: [
      require("./light/1/document/1.png"),
      require("./light/1/document/2.png"),
      require("./light/1/document/3.png"),
      require("./light/1/document/4.png"),
    ],
    event: [
      require("./light/1/event/1.png"),
      require("./light/1/event/2.png"),
      require("./light/1/event/3.png"),
      require("./light/1/event/4.png"),
    ],
    industry: [
      require("./light/1/industry/1.png"),
      require("./light/1/industry/2.png"),
      require("./light/1/industry/3.png"),
      require("./light/1/industry/4.png"),
    ],
    location: [
      require("./light/1/location/1.png"),
      require("./light/1/location/2.png"),
      require("./light/1/location/3.png"),
      require("./light/1/location/4.png"),
    ],
    missile: [
      require("./light/1/missile/1.png"),
      require("./light/1/missile/2.png"),
      require("./light/1/missile/3.png"),
      require("./light/1/missile/4.png"),
    ],
    organization: [
      require("./light/1/organization/1.png"),
      require("./light/1/organization/2.png"),
      require("./light/1/organization/3.png"),
      require("./light/1/organization/4.png"),
    ],
    person: [
      require("./light/1/person/1.png"),
      require("./light/1/person/2.png"),
      require("./light/1/person/3.png"),
      require("./light/1/person/4.png"),
    ],
    rocket: [
      require("./light/1/rocket/1.png"),
      require("./light/1/rocket/2.png"),
      require("./light/1/rocket/3.png"),
      require("./light/1/rocket/4.png"),
    ],
    ship: [
      require("./light/1/ship/1.png"),
      require("./light/1/ship/2.png"),
      require("./light/1/ship/3.png"),
      require("./light/1/ship/4.png"),
    ],
    train: [
      require("./light/1/train/1.png"),
      require("./light/1/train/2.png"),
      require("./light/1/train/3.png"),
      require("./light/1/train/4.png"),
    ],
  },
  2: {
    account: [
      require("./light/2/account/1.png"),
      require("./light/2/account/2.png"),
      require("./light/2/account/3.png"),
      require("./light/2/account/4.png"),
    ],
    airplane: [
      require("./light/2/airplane/1.png"),
      require("./light/2/airplane/2.png"),
      require("./light/2/airplane/3.png"),
      require("./light/2/airplane/4.png"),
    ],
    armoredVehicle: [
      require("./light/2/armoredVehicle/1.png"),
      require("./light/2/armoredVehicle/2.png"),
      require("./light/2/armoredVehicle/3.png"),
      require("./light/2/armoredVehicle/4.png"),
    ],
    car: [
      require("./light/2/car/1.png"),
      require("./light/2/car/2.png"),
      require("./light/2/car/3.png"),
      require("./light/2/car/4.png"),
    ],
    company: [
      require("./light/2/company/1.png"),
      require("./light/2/company/2.png"),
      require("./light/2/company/3.png"),
      require("./light/2/company/4.png"),
    ],
    cruiser: [
      require("./light/2/cruiser/1.png"),
      require("./light/2/cruiser/2.png"),
      require("./light/2/cruiser/3.png"),
      require("./light/2/cruiser/4.png"),
    ],
    default: [
      require("./light/2/default/1.png"),
      require("./light/2/default/2.png"),
      require("./light/2/default/3.png"),
      require("./light/2/default/4.png"),
    ],
    document: [
      require("./light/2/document/1.png"),
      require("./light/2/document/2.png"),
      require("./light/2/document/3.png"),
      require("./light/2/document/4.png"),
    ],
    event: [
      require("./light/2/event/1.png"),
      require("./light/2/event/2.png"),
      require("./light/2/event/3.png"),
      require("./light/2/event/4.png"),
    ],
    industry: [
      require("./light/2/industry/1.png"),
      require("./light/2/industry/2.png"),
      require("./light/2/industry/3.png"),
      require("./light/2/industry/4.png"),
    ],
    location: [
      require("./light/2/location/1.png"),
      require("./light/2/location/2.png"),
      require("./light/2/location/3.png"),
      require("./light/2/location/4.png"),
    ],
    missile: [
      require("./light/2/missile/1.png"),
      require("./light/2/missile/2.png"),
      require("./light/2/missile/3.png"),
      require("./light/2/missile/4.png"),
    ],
    organization: [
      require("./light/2/organization/1.png"),
      require("./light/2/organization/2.png"),
      require("./light/2/organization/3.png"),
      require("./light/2/organization/4.png"),
    ],
    person: [
      require("./light/2/person/1.png"),
      require("./light/2/person/2.png"),
      require("./light/2/person/3.png"),
      require("./light/2/person/4.png"),
    ],
    rocket: [
      require("./light/2/rocket/1.png"),
      require("./light/2/rocket/2.png"),
      require("./light/2/rocket/3.png"),
      require("./light/2/rocket/4.png"),
    ],
    ship: [
      require("./light/2/ship/1.png"),
      require("./light/2/ship/2.png"),
      require("./light/2/ship/3.png"),
      require("./light/2/ship/4.png"),
    ],
    train: [
      require("./light/2/train/1.png"),
      require("./light/2/train/2.png"),
      require("./light/2/train/3.png"),
      require("./light/2/train/4.png"),
    ],
  },
};

const dark = {
  0: {
    account: [
      require("./dark/0/account/1.png"),
      require("./dark/0/account/2.png"),
      require("./dark/0/account/3.png"),
      require("./dark/0/account/4.png"),
    ],
    airplane: [
      require("./dark/0/airplane/1.png"),
      require("./dark/0/airplane/2.png"),
      require("./dark/0/airplane/3.png"),
      require("./dark/0/airplane/4.png"),
    ],
    armoredVehicle: [
      require("./dark/0/armoredVehicle/1.png"),
      require("./dark/0/armoredVehicle/2.png"),
      require("./dark/0/armoredVehicle/3.png"),
      require("./dark/0/armoredVehicle/4.png"),
    ],
    car: [
      require("./dark/0/car/1.png"),
      require("./dark/0/car/2.png"),
      require("./dark/0/car/3.png"),
      require("./dark/0/car/4.png"),
    ],
    company: [
      require("./dark/0/company/1.png"),
      require("./dark/0/company/2.png"),
      require("./dark/0/company/3.png"),
      require("./dark/0/company/4.png"),
    ],
    cruiser: [
      require("./dark/0/cruiser/1.png"),
      require("./dark/0/cruiser/2.png"),
      require("./dark/0/cruiser/3.png"),
      require("./dark/0/cruiser/4.png"),
    ],
    default: [
      require("./dark/0/default/1.png"),
      require("./dark/0/default/2.png"),
      require("./dark/0/default/3.png"),
      require("./dark/0/default/4.png"),
    ],
    document: [
      require("./dark/0/document/1.png"),
      require("./dark/0/document/2.png"),
      require("./dark/0/document/3.png"),
      require("./dark/0/document/4.png"),
    ],
    event: [require("./dark/0/event/1.png")],
    industry: [
      require("./dark/0/industry/1.png"),
      require("./dark/0/industry/2.png"),
      require("./dark/0/industry/3.png"),
      require("./dark/0/industry/4.png"),
    ],
    location: [
      require("./dark/0/location/1.png"),
      require("./dark/0/location/2.png"),
      require("./dark/0/location/3.png"),
      require("./dark/0/location/4.png"),
    ],
    missile: [
      require("./dark/0/missile/1.png"),
      require("./dark/0/missile/2.png"),
      require("./dark/0/missile/3.png"),
      require("./dark/0/missile/4.png"),
    ],
    organization: [
      require("./dark/0/organization/1.png"),
      require("./dark/0/organization/2.png"),
      require("./dark/0/organization/3.png"),
      require("./dark/0/organization/4.png"),
    ],
    person: [
      require("./dark/0/person/1.png"),
      require("./dark/0/person/2.png"),
      require("./dark/0/person/3.png"),
      require("./dark/0/person/4.png"),
    ],
    rocket: [
      require("./dark/0/rocket/1.png"),
      require("./dark/0/rocket/2.png"),
      require("./dark/0/rocket/3.png"),
      require("./dark/0/rocket/4.png"),
    ],
    ship: [
      require("./dark/0/ship/1.png"),
      require("./dark/0/ship/2.png"),
      require("./dark/0/ship/3.png"),
      require("./dark/0/ship/4.png"),
    ],
    train: [
      require("./dark/0/train/1.png"),
      require("./dark/0/train/2.png"),
      require("./dark/0/train/3.png"),
      require("./dark/0/train/4.png"),
    ],
  },
};

const lightIcon = JSON.stringify(light);
const darkIcon = JSON.stringify(dark);
export default { lightIcon, darkIcon };

export const defaultIcon = {
  account: {
    1: [
      require("./default/account/1/1.svg"),
      require("./default/account/1/2.svg"),
      require("./default/account/1/3.svg"),
      require("./default/account/1/4.svg"),
      require("./default/account/1/5.svg"),
      require("./default/account/1/6.svg"),
      require("./default/account/1/7.svg"),
      require("./default/account/1/8.svg"),
      require("./default/account/1/9.svg"),
      require("./default/account/1/10.svg"),
      require("./default/account/1/11.svg"),
      require("./default/account/1/12.svg"),
      require("./default/account/1/13.svg"),
      require("./default/account/1/14.svg"),
      require("./default/account/1/15.svg"),
      require("./default/account/1/16.svg"),
      require("./default/account/1/17.svg"),
      require("./default/account/1/18.svg"),
      require("./default/account/1/19.svg"),
      require("./default/account/1/20.svg"),
    ],
    2: [
      require("./default/account/2/1.svg"),
      require("./default/account/2/2.svg"),
      require("./default/account/2/3.svg"),
      require("./default/account/2/4.svg"),
      require("./default/account/2/5.svg"),
      require("./default/account/2/6.svg"),
      require("./default/account/2/7.svg"),
      require("./default/account/2/8.svg"),
      require("./default/account/2/9.svg"),
      require("./default/account/2/10.svg"),
      require("./default/account/2/11.svg"),
      require("./default/account/2/12.svg"),
      require("./default/account/2/13.svg"),
      require("./default/account/2/14.svg"),
      require("./default/account/2/15.svg"),
      require("./default/account/2/16.svg"),
      require("./default/account/2/17.svg"),
      require("./default/account/2/18.svg"),
      require("./default/account/2/19.svg"),
      require("./default/account/2/20.svg"),
    ],
    3: [
      require("./default/account/3/1.svg"),
      require("./default/account/3/2.svg"),
      require("./default/account/3/3.svg"),
      require("./default/account/3/4.svg"),
      require("./default/account/3/5.svg"),
      require("./default/account/3/6.svg"),
      require("./default/account/3/7.svg"),
      require("./default/account/3/8.svg"),
      require("./default/account/3/9.svg"),
      require("./default/account/3/10.svg"),
      require("./default/account/3/11.svg"),
      require("./default/account/3/12.svg"),
      require("./default/account/3/13.svg"),
      require("./default/account/3/14.svg"),
      require("./default/account/3/15.svg"),
      require("./default/account/3/16.svg"),
      require("./default/account/3/17.svg"),
      require("./default/account/3/18.svg"),
      require("./default/account/3/19.svg"),
      require("./default/account/3/20.svg"),
    ],
  },
  article: {
    1: [
      require("./default/article/1/1.svg"),
      require("./default/article/1/2.svg"),
      require("./default/article/1/3.svg"),
      require("./default/article/1/4.svg"),
      require("./default/article/1/5.svg"),
      require("./default/article/1/6.svg"),
      require("./default/article/1/7.svg"),
      require("./default/article/1/8.svg"),
      require("./default/article/1/9.svg"),
      require("./default/article/1/10.svg"),
      require("./default/article/1/11.svg"),
      require("./default/article/1/12.svg"),
      require("./default/article/1/13.svg"),
      require("./default/article/1/14.svg"),
      require("./default/article/1/15.svg"),
      require("./default/article/1/16.svg"),
      require("./default/article/1/17.svg"),
      require("./default/article/1/18.svg"),
      require("./default/article/1/19.svg"),
      require("./default/article/1/20.svg"),
    ],
    2: [
      require("./default/article/2/1.svg"),
      require("./default/article/2/2.svg"),
      require("./default/article/2/3.svg"),
      require("./default/article/2/4.svg"),
      require("./default/article/2/5.svg"),
      require("./default/article/2/6.svg"),
      require("./default/article/2/7.svg"),
      require("./default/article/2/8.svg"),
      require("./default/article/2/9.svg"),
      require("./default/article/2/10.svg"),
      require("./default/article/2/11.svg"),
      require("./default/article/2/12.svg"),
      require("./default/article/2/13.svg"),
      require("./default/article/2/14.svg"),
      require("./default/article/2/15.svg"),
      require("./default/article/2/16.svg"),
      require("./default/article/2/17.svg"),
      require("./default/article/2/18.svg"),
      require("./default/article/2/19.svg"),
      require("./default/article/2/20.svg"),
    ],
    3: [
      require("./default/article/3/1.svg"),
      require("./default/article/3/2.svg"),
      require("./default/article/3/3.svg"),
      require("./default/article/3/4.svg"),
      require("./default/article/3/5.svg"),
      require("./default/article/3/6.svg"),
      require("./default/article/3/7.svg"),
      require("./default/article/3/8.svg"),
      require("./default/article/3/9.svg"),
      require("./default/article/3/10.svg"),
      require("./default/article/3/11.svg"),
      require("./default/article/3/12.svg"),
      require("./default/article/3/13.svg"),
      require("./default/article/3/14.svg"),
      require("./default/article/3/15.svg"),
      require("./default/article/3/16.svg"),
      require("./default/article/3/17.svg"),
      require("./default/article/3/18.svg"),
      require("./default/article/3/19.svg"),
      require("./default/article/3/20.svg"),
    ],
  },
  bank: {
    1: [
      require("./default/bank/1/1.svg"),
      require("./default/bank/1/2.svg"),
      require("./default/bank/1/3.svg"),
      require("./default/bank/1/4.svg"),
      require("./default/bank/1/5.svg"),
      require("./default/bank/1/6.svg"),
      require("./default/bank/1/7.svg"),
      require("./default/bank/1/8.svg"),
      require("./default/bank/1/9.svg"),
      require("./default/bank/1/10.svg"),
      require("./default/bank/1/11.svg"),
      require("./default/bank/1/12.svg"),
      require("./default/bank/1/13.svg"),
      require("./default/bank/1/14.svg"),
      require("./default/bank/1/15.svg"),
      require("./default/bank/1/16.svg"),
      require("./default/bank/1/17.svg"),
      require("./default/bank/1/18.svg"),
      require("./default/bank/1/19.svg"),
      require("./default/bank/1/20.svg"),
    ],
    2: [
      require("./default/bank/2/1.svg"),
      require("./default/bank/2/2.svg"),
      require("./default/bank/2/3.svg"),
      require("./default/bank/2/4.svg"),
      require("./default/bank/2/5.svg"),
      require("./default/bank/2/6.svg"),
      require("./default/bank/2/7.svg"),
      require("./default/bank/2/8.svg"),
      require("./default/bank/2/9.svg"),
      require("./default/bank/2/10.svg"),
      require("./default/bank/2/11.svg"),
      require("./default/bank/2/12.svg"),
      require("./default/bank/2/13.svg"),
      require("./default/bank/2/14.svg"),
      require("./default/bank/2/15.svg"),
      require("./default/bank/2/16.svg"),
      require("./default/bank/2/17.svg"),
      require("./default/bank/2/18.svg"),
      require("./default/bank/2/19.svg"),
      require("./default/bank/2/20.svg"),
    ],
    3: [
      require("./default/bank/3/1.svg"),
      require("./default/bank/3/2.svg"),
      require("./default/bank/3/3.svg"),
      require("./default/bank/3/4.svg"),
      require("./default/bank/3/5.svg"),
      require("./default/bank/3/6.svg"),
      require("./default/bank/3/7.svg"),
      require("./default/bank/3/8.svg"),
      require("./default/bank/3/9.svg"),
      require("./default/bank/3/10.svg"),
      require("./default/bank/3/11.svg"),
      require("./default/bank/3/12.svg"),
      require("./default/bank/3/13.svg"),
      require("./default/bank/3/14.svg"),
      require("./default/bank/3/15.svg"),
      require("./default/bank/3/16.svg"),
      require("./default/bank/3/17.svg"),
      require("./default/bank/3/18.svg"),
      require("./default/bank/3/19.svg"),
      require("./default/bank/3/20.svg"),
    ],
  },
  company: {
    1: [
      require("./default/company/1/1.svg"),
      require("./default/company/1/2.svg"),
      require("./default/company/1/3.svg"),
      require("./default/company/1/4.svg"),
      require("./default/company/1/5.svg"),
      require("./default/company/1/6.svg"),
      require("./default/company/1/7.svg"),
      require("./default/company/1/8.svg"),
      require("./default/company/1/9.svg"),
      require("./default/company/1/10.svg"),
      require("./default/company/1/11.svg"),
      require("./default/company/1/12.svg"),
      require("./default/company/1/13.svg"),
      require("./default/company/1/14.svg"),
      require("./default/company/1/15.svg"),
      require("./default/company/1/16.svg"),
      require("./default/company/1/17.svg"),
      require("./default/company/1/18.svg"),
      require("./default/company/1/19.svg"),
      require("./default/company/1/20.svg"),
    ],
    2: [
      require("./default/company/2/1.svg"),
      require("./default/company/2/2.svg"),
      require("./default/company/2/3.svg"),
      require("./default/company/2/4.svg"),
      require("./default/company/2/5.svg"),
      require("./default/company/2/6.svg"),
      require("./default/company/2/7.svg"),
      require("./default/company/2/8.svg"),
      require("./default/company/2/9.svg"),
      require("./default/company/2/10.svg"),
      require("./default/company/2/11.svg"),
      require("./default/company/2/12.svg"),
      require("./default/company/2/13.svg"),
      require("./default/company/2/14.svg"),
      require("./default/company/2/15.svg"),
      require("./default/company/2/16.svg"),
      require("./default/company/2/17.svg"),
      require("./default/company/2/18.svg"),
      require("./default/company/2/19.svg"),
      require("./default/company/2/20.svg"),
    ],
    3: [
      require("./default/company/3/1.svg"),
      require("./default/company/3/2.svg"),
      require("./default/company/3/3.svg"),
      require("./default/company/3/4.svg"),
      require("./default/company/3/5.svg"),
      require("./default/company/3/6.svg"),
      require("./default/company/3/7.svg"),
      require("./default/company/3/8.svg"),
      require("./default/company/3/9.svg"),
      require("./default/company/3/10.svg"),
      require("./default/company/3/11.svg"),
      require("./default/company/3/12.svg"),
      require("./default/company/3/13.svg"),
      require("./default/company/3/14.svg"),
      require("./default/company/3/15.svg"),
      require("./default/company/3/16.svg"),
      require("./default/company/3/17.svg"),
      require("./default/company/3/18.svg"),
      require("./default/company/3/19.svg"),
      require("./default/company/3/20.svg"),
    ],
  },
  person: {
    1: [
      require("./default/person/1/1.svg"),
      require("./default/person/1/2.svg"),
      require("./default/person/1/3.svg"),
      require("./default/person/1/4.svg"),
      require("./default/person/1/5.svg"),
      require("./default/person/1/6.svg"),
      require("./default/person/1/7.svg"),
      require("./default/person/1/8.svg"),
      require("./default/person/1/9.svg"),
      require("./default/person/1/10.svg"),
      require("./default/person/1/11.svg"),
      require("./default/person/1/12.svg"),
      require("./default/person/1/13.svg"),
      require("./default/person/1/14.svg"),
      require("./default/person/1/15.svg"),
      require("./default/person/1/16.svg"),
      require("./default/person/1/17.svg"),
      require("./default/person/1/18.svg"),
      require("./default/person/1/19.svg"),
      require("./default/person/1/20.svg"),
    ],
    2: [
      require("./default/person/2/1.svg"),
      require("./default/person/2/2.svg"),
      require("./default/person/2/3.svg"),
      require("./default/person/2/4.svg"),
      require("./default/person/2/5.svg"),
      require("./default/person/2/6.svg"),
      require("./default/person/2/7.svg"),
      require("./default/person/2/8.svg"),
      require("./default/person/2/9.svg"),
      require("./default/person/2/10.svg"),
      require("./default/person/2/11.svg"),
      require("./default/person/2/12.svg"),
      require("./default/person/2/13.svg"),
      require("./default/person/2/14.svg"),
      require("./default/person/2/15.svg"),
      require("./default/person/2/16.svg"),
      require("./default/person/2/17.svg"),
      require("./default/person/2/18.svg"),
      require("./default/person/2/19.svg"),
      require("./default/person/2/20.svg"),
    ],
    3: [
      require("./default/person/3/1.svg"),
      require("./default/person/3/2.svg"),
      require("./default/person/3/3.svg"),
      require("./default/person/3/4.svg"),
      require("./default/person/3/5.svg"),
      require("./default/person/3/6.svg"),
      require("./default/person/3/7.svg"),
      require("./default/person/3/8.svg"),
      require("./default/person/3/9.svg"),
      require("./default/person/3/10.svg"),
      require("./default/person/3/11.svg"),
      require("./default/person/3/12.svg"),
      require("./default/person/3/13.svg"),
      require("./default/person/3/14.svg"),
      require("./default/person/3/15.svg"),
      require("./default/person/3/16.svg"),
      require("./default/person/3/17.svg"),
      require("./default/person/3/18.svg"),
      require("./default/person/3/19.svg"),
      require("./default/person/3/20.svg"),
    ],
  },
};